language: python
python:
    - "3.5"
env:
    global:
        - secure: z/+0nCkruJ2BeKna5nWOFDCFL/5atQ/Lh1sqniH5W1TJ3ZP02mO3CUmMkzuBB0o4TDmcksrTMaZZ3pq53jIEaRA5AYkCaE2l4n6lIQEbSoqRboRbOM/ocYgLE03qi5EQHQ+59WkKGd1J8lRLqzLxNfJ1OiUWbJmUMq6mwOB16AZ8zhXoknIavinodLWHFM9OhBz1cen6gLPmbXXfVJWu+PTGWxZnAg1mV1WukrMAHSv/IQ6sXCPctbPjR3PPxA0jpfTB1IXOdogAtMZ0TBS0pmIScZhgD7xxAFNzwds/p9n95uQYPXEYOkTb3NF7Y9dzKVzLXPTaGqOmXz9gfbHl3m2mw4YrhRQm3MQ91xtJwcnz5wk8odeaUJJXoGLxt/KxFtFNN2QjnvMbTiSKpJWanAW7VI+4VUi2SKuHZjG+zTntxZg96sI5RZIxSJoYo2jL2K19PIdKGWUR415F5svj9uD66ibyBojeZNpydv6vjsZ2Bx1oPInGNLtZcDxGpO1Pzht03eFeUNidA4HTWRqsUTbxZIABNL2fvKgAkafDVFw3H+VmeSByPJnqLKZRa9rk+oC5mSHBp1mFs0KVfbn+kcj7fcklk5Ye0Sazc+GzTQRcqbjTG25izenpQcU4m3o5uE1pFobXWan1g7Zn4l/3jJmDH3pkkZhtn2WFGeUaJYM=
        - secure: wzvZE71P3MswKHjY0iXW8R0b0DApTSbNuS7eyR1ppFQOLNNYdZFdWwppvIGDs1GXCH1lTcfl+cZWbvBmchSPYhRj1QLya1K2pTkAhFFTg3WvmZHKiHV8SCgWN8O5ykl2Qcddj6gP3baQ1LzljOOJ1vnTcPArKo5EJiXJqziQF71zB4lfzRNCggPT0HETQy/Upi6DSCUKwCxKyAygusg/FGLwX7MyT4fAnjulXH1fnE2RTY7GO/morNIl+iLVEKKbkMdxRBEMaRnu3iMRfNp4ABMN2HXpDF4C/Z9YAkZyg93juglB89l1yxO9IJP3yCm30bQFdZ254hLM8smFk2C3S3PGwL0tXG/YfvS+5PNvqjcWL04wko1USeSbTexMAky+nlNs6qN0nQe8xyUV2G+3GCPs+7QW+p9llN8ZrDu49pcs9LHm/TBM8ES2gHgZmNru2QQZ2pa6B0MTFpFaUZpRVZ9XQsZFkx9lhQBNbmpar8tT/wHfjC56ufd+I6JirjITc9pCSW0CFpMf+ACZS1D++dgCMh4aLVh5ET55hrOS0QThCDzzpSdcezKsP7rwrkrV8igAkelOsTNX6j5V/QjRDsS8/YLnMRQdV1n5fM4rwa9lytVJ1p+nMlqetxYY9dvnvXLgzHajT/D/6b2rwnf7SIPvKQr4Udv90B6DokQq03M=
addons:
    postgresql: "9.5"
services:
    - postgresql
before_install:
    - pip install -U pip
    - pip install poetry
install:
    - poetry install
before_script:
    - psql -c "create database dpgs_sandbox;" -U postgres
script:
    - ./dpgs_sandbox/await-postgres.sh && poetry run python dpgs_sandbox/manage.py test tests
after_success:
    - codecov
before_deploy:
    - poetry build
deploy:
    provider: script
    script: poetry publish -u $PYPI_USER -p $PYPI_PWD
    skip_cleanup: true
    on:
        tags: true
